config/routes.rb
HackSubmit::Application.routes.draw do
  resources :event_sources do
    member do
      post 'load_events'
    end
  end

  resources :events do
    member do
      post 'toggle_hidden'
      post 'shuffle'
      get 'raffle'
      get 'order'
    end
    resources :hacks do
      post 'confirm_member'
      post 'remove_member'
      post 'join'
      post 'submit'
      post 'like'
      post 'unlike'
    end
  end

  root :to => 'events#home'

end

app/models/event_source.rb
require "net/http"
require "net/https"

class EventSource < ActiveRecord::Base
  attr_accessible :fbid
  validates_uniqueness_of :fbid
  has_many :events

  def name
    if @source_name.nil?
      uri = URI::parse("http://graph.facebook.com/" + self.fbid)
      response = Net::HTTP.get_response(uri)
      body = response.body
      obj = JSON.parse(body)
      @source_name = obj['name'] || "Error finding name"
    end

    return @source_name
  end

  def reload_events!(api)
      return if api.nil?
      #events = api.get_connections(fbid, 'events')
      query = "
        SELECT
          eid,
          name,
          start_time,
          end_time,
          timezone
        FROM event
        WHERE
          eid IN (
            SELECT eid FROM event_member WHERE uid = '#{fbid}' AND start_time > 0
          )
        ORDER BY start_time DESC"
      events = api.fql_query(query)

      events.each do |event_obj|
        fbid = event_obj['eid'].to_s
        event = Event.where(:fbid => fbid).first || Event.new(:fbid => fbid)
        event.name = event_obj['name']
        event.event_source = self
        event.time_start = Time.parse(event_obj['start_time'])
        event.time_end = Time.parse(event_obj['end_time'] || event_obj['start_time'])
        event.timezone = event_obj['timezone'] || 'UTC'
        event.save!
      end
  end
end

app/controllers/event_sources_controller.rb
class EventSourcesController < ApplicationController
  load_and_authorize_resource

  # GET /event_sources
  # GET /event_sources.json
  def index
    @event_sources = EventSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @event_sources }
    end
  end

  # GET /event_sources/1
  # GET /event_sources/1.json
  def show
    @event_source = EventSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event_source }
    end
  end

  # GET /event_sources/new
  # GET /event_sources/new.json
  def new
    @event_source = EventSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event_source }
    end
  end

  # GET /event_sources/1/edit
  def edit
    @event_source = EventSource.find(params[:id])
  end

  # POST /event_sources
  # POST /event_sources.json
  def create
    @event_source = EventSource.new(params[:event_source])

    respond_to do |format|
      if @event_source.save
        format.html { redirect_to @event_source, :notice => 'Event source was successfully created.' }
        format.json { render :json => @event_source, :status => :created, :location => @event_source }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /event_sources/1
  # PUT /event_sources/1.json
  def update
    @event_source = EventSource.find(params[:id])

    respond_to do |format|
      if @event_source.update_attributes(params[:event_source])
        format.html { redirect_to @event_source, :notice => 'Event source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /event_sources/1
  # DELETE /event_sources/1.json
  def destroy
    @event_source = EventSource.find(params[:id])
    @event_source.destroy

    respond_to do |format|
      format.html { redirect_to event_sources_url }
      format.json { head :no_content }
    end
  end

  def load_events
    @event_source = EventSource.find(params[:id])

    @event_source.reload_events!(@api)

    redirect_to event_sources_path
  end
end

app/helpers/event_sources_helper.rb
module EventSourcesHelper
end

app/views/event_sources/_form.html.erb
<%= form_for(@event_source) do |f| %>
  <% if @event_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_source.errors.count, "error") %> prohibited this event_source from being saved:</h2>

      <ul>
      <% @event_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fbid %><br />
    <%= f.text_field :fbid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_sources/edit.html.erb
<h1>Editing event_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_source %> |
<%= link_to 'Back', event_sources_path %>

app/views/event_sources/index.html.erb
<h1>Listing event_sources</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Page</th>
      <th>FBID</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @event_sources.each do |event_source| %>
  <tr>
    <td>
      <%= link_to event_source.name, 'https://www.facebook.com/' + event_source.fbid %>
    </td>
    <td>
      <%= event_source.fbid %>
    </td>
    <td><%= link_to 'Load upcoming events', load_events_event_source_path(event_source), :method => :post %></td>
    <td><%= link_to 'Destroy', event_source, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Event source', new_event_source_path %>

app/views/event_sources/new.html.erb
<h1>New event_source</h1>

<%= render 'form' %>

<%= link_to 'Back', event_sources_path %>

app/views/event_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fbid:</b>
  <%= @event_source.fbid %>
</p>


<%= link_to 'Edit', edit_event_source_path(@event_source) %> |
<%= link_to 'Back', event_sources_path %>