config/routes.rb
HackSubmit::Application.routes.draw do
  resources :event_sources do
    member do
      post 'load_events'
    end
  end

  resources :events do
    member do
      post 'toggle_hidden'
      post 'shuffle'
      get 'raffle'
      get 'order'
    end
    resources :hacks do
      post 'confirm_member'
      post 'remove_member'
      post 'join'
      post 'submit'
      post 'like'
      post 'unlike'
    end
  end

  root :to => 'events#home'

end

app/models/hack.rb
class Hack < ActiveRecord::Base
  belongs_to :event
  has_many :hack_members_assocs, :dependent => :destroy
  has_many :confirmed_members_assocs, :source => :hack_members_assocs, :class_name => 'HackMembersAssoc', :conditions => {:confirmed => true}
  has_many :unconfirmed_members_assocs, :source => :hack_members_assocs, :class_name => 'HackMembersAssoc', :conditions => {:confirmed => false}
  has_many :confirmed_members, :through => :confirmed_members_assocs, :source => :user, :class_name => 'User'
  has_many :unconfirmed_members, :through => :unconfirmed_members_assocs, :source => :user, :class_name => 'User'

  attr_accessible :description, :image_url, :name, :source_url, :url, :first
  validates :name, :description, :event, :presence => true
  validates_format_of :url, :image_url, :source_url, :with => URI::regexp(%w(http https)), :allow_blank => true

  def sort_rand
    self[:sort_rand] + (self.first ? 1 : 0)
  end

  def submitted?
    !published_fbid.blank?
  end

  def likes?(user, api)
    likes(api).include?(user.fbid)
  end

  def likes(api)
    return [] if api.nil? || !submitted?
    Rails.cache.fetch(likes_key, :expires_in => 2.minutes) do
      likes = []
      post = api.get_object(published_fbid)
      unless post.nil?
        raw_likes = post.has_key?('likes') ? post['likes']['data'] : []
        raw_likes.each do |row|
          likes.push row['id']
        end
      end

      likes
    end
  end

  def like_count(api)
    return likes(api).length
  end

  def likes_key
    published_fbid.nil? ? nil : (published_fbid + ':likes')
  end

  def clear_like_cache
    Rails.cache.delete(likes_key)
  end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_filter :load_hack, :except => [:new, :create]
  before_filter :load_event
  before_filter :verify_event, :except => [:new, :show, :create]

  # GET /hacks/1
  # GET /hacks/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @hack }
    end
  end

  def submit
    data = {}
    data[:message] = @hack.description
    data[:link] = @hack.url unless @hack.url.blank?
    data[:picture] = @hack.image_url unless @hack.image_url.blank?
    data[:name] = @hack.name
    data[:place] = @event.event_source.fbid
    fbids = []
    @hack.confirmed_members.each do |user|
      fbids.push user.fbid
    end
    data[:tags] = fbids.join(',')
    begin
      result = @api.put_connections(@event.fbid, "feed", data)
      @hack.published_fbid = result['id']
      @hack.save!
    rescue Koala::Facebook::APIError => e
      flash[:errors] = [e.message]
    end
    
    redirect_to @event
  end

  def like
    @api.put_like(@hack.published_fbid)
    @hack.clear_like_cache
    redirect_to @event
  end

  def unlike
    @api.delete_like(@hack.published_fbid)
    @hack.clear_like_cache
    redirect_to @event
  end

  # GET /hacks/1/edit
  def edit
  end
  
  # GET /hacks/
  def new
    @hack = Hack.new
    @friends = []
  end

  # POST /hacks
  # POST /hacks.json
  def create
    @friends = params[:friends] || []
    @hack = Hack.new(params[:hack])
    @hack.sort_rand = Random.rand
    @hack.event_id = @event.id

    if !@hack.save
      respond_to do |format|
        format.html { render :action => "new" }
        format.json { render :json => @hack.errors, :status => :unprocessable_entity }
      end
      return
    end

    assoc = HackMembersAssoc.new
    assoc.hack = @hack
    assoc.user = @current_user
    assoc.confirmed = true
    assoc.save!
    @friends.each do |friend_id|
      friend = User.get_or_create_by_fbid(friend_id, @api);
      assoc = HackMembersAssoc.new
      assoc.hack = @hack
      assoc.user = friend
      assoc.confirmed = true
      assoc.save!
    end

    respond_to do |format|
      format.html { redirect_to @event, :notices => ['Hack was successfully created.'] }
      format.json { render :json => @hack, :status => :created, :location => [@event, @hack] }
    end
  end

  # PUT /hacks/1
  # PUT /hacks/1.json
  def update
    respond_to do |format|
      if @hack.update_attributes(params[:hack])
        format.html { redirect_to @event, :notices => ['Hack was successfully updated.'] }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @hack.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hacks/1
  # DELETE /hacks/1.json
  def destroy
    @hack.destroy

    respond_to do |format|
      format.html { redirect_to event_url(@event) }
      format.json { head :no_content }
    end
  end

  def join
    assoc = HackMembersAssoc.new
    assoc.hack = @hack
    assoc.user = @current_user
    assoc.save!
    
    redirect_to @event
  end

  def confirm_member
    assocs = HackMembersAssoc.where(:hack_id => @hack.id, :user_id => params[:user_id]).all
    assocs.each do |assoc|
      assoc.confirmed = true
      assoc.save!
    end

    redirect_to edit_event_hack_path(@event, @hack)
  end

  def remove_member
    assocs = HackMembersAssoc.where(:hack_id => @hack.id, :user_id => params[:user_id]).all
    assocs.each do |assoc|
      assoc.destroy
    end

    redirect_to edit_event_hack_path(@event, @hack)
  end

  private

  def load_hack
    if @hack.nil?
      id = params[:id] || params[:hack_id]
      @hack = Hack.find(id)
    end
    
    authorize!(params[:action].to_sym, @hack)
  end

  def load_event
    @event = Event.find_by_fbid(params[:event_id])
  end

  def verify_event
    @hack.event_id == @event.id or raise "Hack does not belong to event"
  end

end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hacks/_form.html.erb
<div style="width: 650px">
<%= form_for([@event, @hack]) do |f| %>
  <% if @hack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hack.errors.count, "error") %> prohibited this hack from being saved:</h2>

      <ul>
      <% @hack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => 'AwesomeHack', :required => 'required' %>
  
  <%= f.label :description %>
  <%= f.text_area :description, :rows => 6, :class => 'span5', :placeholder => 'One or two sentences about what your hack does and why you built it (required)', :required => 'required' %>
  
  <%= f.label :url %>
  <%= f.text_field :url, :placeholder => 'http://www.facebook.com/', :class => 'span5' %>
  
  <%= f.label :source_url %>
  <%= f.text_field :source_url, :placeholder => 'http://www.github.com/facebook/', :class => 'span5' %>
  
  <%= f.label :image_url %>
  <%= f.text_field :image_url, :placeholder => 'http://i.imgur.com/bwAFI.jpg', :class => 'span5' %>

  <% if @hack.new_record? %>
    <label>Who did you work with? (You can add/remove people later)</label>
    <%= javascript_tag do %>
      friends_selected = <%= raw(@friends.to_json) %>;
    <% end %>
    <div id="jfmfs-container"></div>
  <% else %>
    <label>Confirmed Team Members (click to remove)</label>
    <div class="facepile">
    <% @hack.confirmed_members.each do |user| %>
      <%= link_to(
        avatar_tag(user),
        event_hack_remove_member_path(@event, @hack, :user_id => user.id),
        :method => :post,
        :data => {:confirm => "Are you sure you want to remove #{user.name}?"}
      ) %>
    <% end %>
    </div>
  
    <% unless @hack.unconfirmed_members.empty? %>
      <label>Unconfirmed Team Members (click to confirm)</label>
      <div class="facepile">
      <% @hack.unconfirmed_members.each do |user| %>
        <%= link_to(
          avatar_tag(user),
          event_hack_confirm_member_path(@event, @hack, :user_id => user.id),
          :method => :post
        ) %>
      <% end %>
      </div>
    <% end %>
  <% end %>
  
  <label class="checkbox important">
      We need to present first because we need to leave or can't use the demo machine
    <%= f.check_box :first %>
  </label>
  <br />
  <%= f.submit :class => 'btn btn-success', :value => (@hack.new_record? ? 'Create Hack' : 'Update Hack'), :onclick => 'read_friend_list(this);' %>
<% end %>
</div>

app/views/hacks/_listing.html.erb
<li id="hack_listing_<%= listing.id %>">
  <div class="row">
    <div class="span3">
      <div class="hack_image_div">
        <% if listing.image_url.blank? %>
          <%= image_tag 'no_image.png', :class => 'hack_image' %>
        <% else %>
          <%= link_to listing.image_url do %>
            <%= image_tag listing.image_url, :class => 'hack_image' %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="span9">
      <h3><%= link_to listing.name, :anchor => "hack_listing_#{listing.id}" %></h3>
      <% if (listing.submitted? && @api) && !presentation %>
        <h4><%= link_to "Likes: #{listing.like_count(@api)}", "//www.facebook.com/#{listing.published_fbid}" %></h4>
      <% end %>
      <p><%= listing.description %></p>
      <ul class="unstyled">
        <% unless listing.url.blank? %>
          <li>
            <strong>Link:</strong>
            <%= link_to listing.url, listing.url %>
          </li>
        <% end %>
        <% unless listing.source_url.blank? %>
          <li>
            <strong>Source Code:</strong>
            <%= link_to listing.source_url, listing.source_url %>
          </li>
        <% end %>
        <li>
          <strong>Built by:</strong><br />
          <% listing.confirmed_members.each do |user| %>
              <%= link_to(
                avatar_tag(user),
                fb_user_path(user)
              ) %>
          <% end %>
        </li>
        <% if !presentation %>
        <% if can?(:edit, listing) && !listing.unconfirmed_members.empty? %>
          <li>
            <strong>Unconfirmed Teamates:</strong><br />
            <% listing.unconfirmed_members.each do |user| %>
                <%= link_to(
                  avatar_tag(user),
                  fb_user_path(user)
                ) %>
            <% end %>
          </li>
        <% elsif !listing.confirmed_member_ids.include?(@current_user.id) && !listing.unconfirmed_member_ids.include?(@current_user.id) && can?(:join, @hack) %>
          <li>
            <%= link_to 'I worked on this!', event_hack_join_path(@event, listing), :method => :post if can?(:join, @hack) %>
          </li>
        <% end %>
        <% if listing.submitted? && (can?(:like, listing) || can?(:unlike, listing)) %>
        <li>
          <% unless listing.likes?(@current_user, @api) %>
            <%= button_to 'Like Hack', event_hack_like_path(@event, listing), :form_class => 'button_to_form', :class => 'btn btn-large btn-success' if can? :like, listing %>
          <% else %>
            <%= button_to 'Unlike Hack', event_hack_unlike_path(@event, listing), :form_class => 'button_to_form', :class => 'btn btn-small btn-link' if can? :unlike, listing %>
          <% end %>
        </li>
        <% end %>
        <% if can?(:submit, listing) %>
          <li>
            <%= button_to 'Submit Hack', event_hack_submit_path(@event, listing), :form_class => 'button_to_form', :class => 'btn btn-large btn-primary' if can? :submit, listing %>
          </li>
        <% end %>
        <% if can?(:edit, listing) || can?(:destroy, listing) %>
          <li>
            <strong>Admin:</strong>
            <%= button_to 'Edit', edit_event_hack_path(@event, listing), :method => :get, :form_class => 'button_to_form', :class => 'btn btn-mini btn-warning' if can? :edit, listing %>
            <%= button_to 'Delete', event_hack_path(@event, listing), :form_class => 'button_to_form', :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-mini btn-danger' if can? :destroy, listing %>
          </li>
        <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</li>

app/views/hacks/edit.html.erb
<%= render :partial => 'events/header' %>
<h2>Editing <%= @hack.name %></h2>

<%= render 'form' %>

app/views/hacks/index.html.erb
<h1>Listing hacks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Url</th>
    <th>Source url</th>
    <th>Image url</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hacks.each do |hack| %>
  <tr>
    <td><%= hack.name %></td>
    <td><%= hack.description %></td>
    <td><%= hack.url %></td>
    <td><%= hack.source_url %></td>
    <td><%= hack.image_url %></td>
    <td><%= hack.event_id %></td>
    <td><%= link_to 'Show', event_hack %></td>
    <td><%= link_to 'Edit', event_hack_path(hack) %></td>
    <td><%= link_to 'Destroy', event_hack, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hack', new_event_hack_path %>

app/views/hacks/new.html.erb
<%= render :partial => 'events/header' %>
<h2>Create Hack</h2>

<%= render 'form' %>

app/views/hacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hack.name %>
</p>

<p>
  <b>Description:</b>
  <%= @hack.description %>
</p>

<p>
  <b>Url:</b>
  <%= @hack.url %>
</p>

<p>
  <b>Source url:</b>
  <%= @hack.source_url %>
</p>

<p>
  <b>Image url:</b>
  <%= @hack.image_url %>
</p>

<p>
  <b>Event:</b>
  <%= @hack.event_id %>
</p>


<%= link_to 'Edit', edit_event_hack_path(@event, @hack) %> |
<%= link_to 'Back', @event %>