config/routes.rb
HackSubmit::Application.routes.draw do
  resources :event_sources do
    member do
      post 'load_events'
    end
  end

  resources :events do
    member do
      post 'toggle_hidden'
      post 'shuffle'
      get 'raffle'
      get 'order'
    end
    resources :hacks do
      post 'confirm_member'
      post 'remove_member'
      post 'join'
      post 'submit'
      post 'like'
      post 'unlike'
    end
  end

  root :to => 'events#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :hacks, :dependent => :destroy
  has_many :hacks_in_progress, :source => :hacks, :class_name => 'Hack', :conditions => 'hacks.published_fbid IS NULL'
  has_many :hacks_completed, :source => :hacks, :class_name => 'Hack', :conditions => 'hacks.published_fbid IS NOT NULL'
  belongs_to :event_source
  attr_accessible :fbid, :name, :time_end, :time_start
  validates_uniqueness_of :fbid

  def to_param
    fbid
  end

  def sorted_hacks
    hacks.sort do |a, b|
      a.sort_rand <=> b.sort_rand
    end
  end

  def tz_start
    timezoneize(time_start)
  end

  def tz_end
    timezoneize(time_end)
  end

  def timezoneize(t)
    TZInfo::Timezone.get(timezone).utc_to_local(t)
  end

  def attending?(user, api)
    return true if user.id.nil?
    attendees(api).include?(user.id)
  end

  def attendees(api)
    key = fbid + ':attendees'
    fbids = Rails.cache.fetch(key, :expires_in => 2.minutes) do
      set = {}
      api.get_connections(fbid, 'attending').each do |info|
        if info['rsvp_status'] == 'attending'
          id = info['id']
          set[id] = id
        end
      end

      set.keys
    end

    User.where(:fbid => fbids).all.collect do |u|
      u.id
    end
  end

  def raffle_eligible_users(api)
    user_ids = {}
    hacks.each do |hack|
      hack.confirmed_member_ids.each do |uid|
        user_ids[uid] = uid
      end
    end

    user_ids = user_ids.keys & attendees(api)

    User.where(:id => user_ids)
  end

  def load_old_hacks!(api)
    return if api.nil?

    api.get_connections(fbid, 'feed').each do |post|
      next unless post.has_key?('application') && post['application']['id'] == '136348336398305'

      
      u = post.has_key?('picture') && URI.parse(post['picture'])
      q = u && CGI::parse(u.query)
      
      hack = Hack.find_by_published_fbid(post['id']) || Hack.new
      hack.published_fbid = post['id']
      puts post.inspect
      hack.name = post['name'] || 'Unable to load name'
      hack.description = post['description'] || 'Unable to load description'
      hack.url = post.has_key?('link') ? post['link'] : nil
      hack.image_url = q.instance_of?(Hash) ? q['src'].first : nil
      hack.event_id = self.id
      hack.save!

      user = User.get_or_create_by_fbid(post['from']['id'], api)
      
      assoc = HackMembersAssoc.new
      assoc.hack_id = hack.id
      assoc.user_id = user.id
      assoc.confirmed = true
      assoc.save!
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :load_event, :except => [:index, :home]

  # GET /events
  # GET /events.json
  def index
    authorize!(:index, Event)
    @events = Event.all.sort do |a, b|
      b.time_start <=> a.time_start
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  def home
    authorize!(:home, Event)
    @upcoming_events = []
    @past_events = []
    
    events = Event.where(:hidden => false).sort do |a, b|
      a.time_end <=> b.time_end
    end
    
    now = Time.new
    events.each do |e|
      if e.time_end > now
        @upcoming_events.push e
      else
        @past_events.push e
      end
    end

    @past_events.reverse!

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {:upcoming => @upcoming_events, :past => @past_events } }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @hack = Hack.new(flash[:hack])

    if @current_user.id?
      my_hack_ids = @current_user.hack_ids & @event.hack_ids
      @my_hacks = Hack.where(:id => my_hack_ids)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  def raffle
    @entries = @event.raffle_eligible_users(@api).sort do |a, b|
      a.fbid <=> b.fbid
    end
    
    @winner = @entries.shuffle.pop
  end

  def order
    @hacks = @event.hacks_completed.sort do |a, b|
      b.sort_rand <=> a.sort_rand
    end
  end

  def toggle_hidden
    @event.hidden = !@event.hidden
    @event.save!

    respond_to do |format|
      format.html { redirect_to events_path, :notice => 'Changed hidden status' }
      format.json { render :json => @event, :status => :updated, :location => @event }
    end
  end

  def shuffle
    @event.hacks.each do |hack|
      hack.sort_rand = Random.rand
      hack.save!
    end

    redirect_to order_event_path(@event)
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private

  def load_event
    if @event.nil?
      @event = Event.includes(:hacks_completed => [:confirmed_members, :unconfirmed_members], :hacks_in_progress => [:confirmed_members, :unconfirmed_members]).find_by_fbid!(params[:id])
    end
    
    authorize!(params[:action].to_sym, @event)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fbid %><br />
    <%= f.text_field :fbid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time_start %><br />
    <%= f.datetime_select :time_start %>
  </div>
  <div class="field">
    <%= f.label :time_end %><br />
    <%= f.datetime_select :time_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_header.html.erb
<div id="event_header">
<h1><%= link_to @event.name, @event %></h1>
<h3><%= @event.tz_start.strftime('%l:%M %p, %B %e, %Y') %> to <%= @event.tz_end.strftime('%l:%M %p, %B %e, %Y') %></h3>
<h4><%= link_to('Facebook Event Page', '//www.facebook.com/' + @event.fbid) %></h4>
<% unless @event.attending?(@current_user, @api) %>
<div class="alert alert-info">
  <a class="close" data-dismiss="alert">&times;</a>
  <strong>Warning!</strong> Looks like you aren't attending the <%= link_to 'Facebook event', '//www.facebook.com/' + @event.fbid %>. You can't submit a hack or win a raffle without <%= link_to 'RSVP', '//www.facebook.com/' + @event.fbid %>ing!
</div>
<% end %>
</div>

app/views/events/_listing.html.erb
<% if listing.time_end > Time.now() %>
<h3><%= link_to listing.name, listing %></h3>
<% else %>
<h4><%= link_to listing.name, listing %></h4>
<% end %>
<p>Hacking begins <%= listing.tz_start.strftime('%B %e, %Y') %> at <%= listing.tz_start.strftime('%l:%M %p') %></p>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/home.html.erb
<h1>Upcoming Hacks</h1>

<div class="row">
  <div class="span11 offset1">
    <% if @upcoming_events.empty? %>
      <h3>No upcoming Hacks :(</h3>
    <% else %>
      <ul class="unstyled event_list">
        <%= render :partial => 'listing', :collection => @upcoming_events %>
      </ul>
    <% end %>
  </div>
</div>

<h2>Past Hacks</h2>

<div class="row">
  <div class="span11 offset1">
    <% if @past_events.empty? %>
      <h3>No past Hacks :(</h3>
    <% else %>
      <ul class="unstyled event_list">
        <%= render :partial => 'listing', :collection => @past_events %>
      </ul>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Timezone</th>
      <th>Hidden</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @events.each do |event| %>
  <tr>
    <td>
      <%= link_to event.name, 'https://www.facebook.com/' + event.fbid %>
    </td>
    <td>
      <%= event.time_start %>
    </td>
    <td>
      <%= event.time_end %>
    </td>
    <td>
      <%= event.timezone %>
    </td>
    <td>
      <%= event.hidden ? 'Hidden' : '' %>
    </td>
    <td>
      <%= link_to 'Toggle hidden status', toggle_hidden_event_path(event), :method => :post %>,
      <%= link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
     </td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/order.html.erb
<%= render :partial => 'header' %>

<div id="hacks_body">

<%= button_to 'Shuffle Hacks', shuffle_event_path(@event), :form_class => 'button_to_form', :class => 'btn btn-large btn-warning' if can? :shuffle, @event %>

<h2>Presentation Order</h2>

<ul class="unstyled hack_list">
  <%= render :partial => 'hacks/listing', :collection => @hacks, :locals => {:presentation => true} %>
</ul>

</div>

app/views/events/raffle.html.erb
<%= render :partial => 'header' %>

<div id="raffle_body">
  <% if @winner %>
    <div id="raffle_entries_body">
      <h3>Drawing from...</h3>
      <div id="raffle_entries">
        <% @entries.each do |user| %>
          <%= link_to avatar_tag(user), fb_user_path(user) %>
        <% end %>
      </div>
    </div>
    <div id="raffle_winner_body" style="display: none">
      <h2 id="raffle_winner_teaser">And the Winner is...</h2>
      <div id="raffle_winner" style="display: none">
        <%= avatar_tag(@winner, 'large') %>
        <h3><%= @winner.name %></h3>
        <h4><%= @event.timezoneize(@now).strftime('%l:%M %p') %></h4>
      </div>
    </div>
  <% else %>
    <h2>No entries yet...</h2>
  <% end %>
</div>

app/views/events/show.html.erb
<%= render :partial => 'header' %>

<div id="hacks_body">

<% if @event.time_end > Time.now %>
<%= button_to 'Create a Hack', new_event_hack_path(@event, @hack), :form_class => 'button_to_form', :method => :get, :class => 'btn btn-large btn-success' if can? :create, Hack %>
<% end %>
<%= button_to 'Presentation Order', order_event_path(@event), :method => :get, :form_class => 'button_to_form', :class => 'btn btn-large btn-primary' if can?(:order, @event) && !@event.hacks_completed.empty? %>
<%= button_to 'Raffle a Prize', raffle_event_path(@event), :method => :get, :form_class => 'button_to_form', :class => 'btn btn-large btn-info' if can? :raffle, @event %>

<% if @my_hacks %>
<h2>My Hacks</h2>
<ul class="unstyled hack_list">
  <%= render :partial => 'hacks/listing', :collection => @my_hacks, :locals => {:presentation => false} %>
</ul>
<% end %>

<h2>Completed Hacks</h2>

<% if @event.hacks_completed.empty? %>
  <p>Looks like there aren't any hacks ready yet. Keep working!</p>
<% else %>
<ul class="unstyled hack_list">
  <%= render :partial => 'hacks/listing', :collection => @event.hacks_completed, :locals => {:presentation => false} %>
</ul>
<% end %>

<%= link_to 'Show Hacks in progress', '#', :class => 'btn btn-warning', :id => 'hip_toggle' %>

<div id="hip">
<h2>Hacks in Progress</h2>
<% if @event.hacks_in_progress.empty? %>
  <p>No hacks have been submitted yet. Get cracking!</p>
<% else %>
<ul class="unstyled hack_list">
  <%= render :partial => 'hacks/listing', :collection => @event.hacks_in_progress, :locals => {:presentation => false} %>
</ul>
<% end %>
</div>

</div>